name: api-tests

on:
  workflow_dispatch:
    pull_request: 
        branches: 
          -  main
    pull_request review:
      branches:
        - 'main'
    

jobs:
    api:
        runs-on: ubuntu-latest

 steps:
   - uses: actions/checkout@v4
   - name: Set up JDK 11
     uses: actions/setup-java@v4
     with:
       java-version: '11'
       distribution: temurin
       cache: maven
